// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC77ZV_BDQm5Efpvf5_j7xKitXmmWSMx1w',
    appId: '1:917117046110:web:674ab6998f00d2b96793cf',
    messagingSenderId: '917117046110',
    projectId: 'test-1aa21',
    authDomain: 'test-1aa21.firebaseapp.com',
    storageBucket: 'test-1aa21.firebasestorage.app',
    measurementId: 'G-V2W2K2Q0XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWe85BNzBKymds5BdLpFreyJuQdDd-KjY',
    appId: '1:917117046110:android:a8be0877c7b7763a6793cf',
    messagingSenderId: '917117046110',
    projectId: 'test-1aa21',
    storageBucket: 'test-1aa21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0_sIXjMnxuLP4SpGWsf5VYd_MJR6H5AQ',
    appId: '1:917117046110:ios:3eee1e099ad6ed166793cf',
    messagingSenderId: '917117046110',
    projectId: 'test-1aa21',
    storageBucket: 'test-1aa21.firebasestorage.app',
    iosBundleId: 'com.example.testt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0_sIXjMnxuLP4SpGWsf5VYd_MJR6H5AQ',
    appId: '1:917117046110:ios:3eee1e099ad6ed166793cf',
    messagingSenderId: '917117046110',
    projectId: 'test-1aa21',
    storageBucket: 'test-1aa21.firebasestorage.app',
    iosBundleId: 'com.example.testt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC77ZV_BDQm5Efpvf5_j7xKitXmmWSMx1w',
    appId: '1:917117046110:web:158f3784786d6fb26793cf',
    messagingSenderId: '917117046110',
    projectId: 'test-1aa21',
    authDomain: 'test-1aa21.firebaseapp.com',
    storageBucket: 'test-1aa21.firebasestorage.app',
    measurementId: 'G-8XE8HLVJBX',
  );
}
